// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mes/inspect/Inspect.proto

package com.inspect;

public interface InspectListReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:inspect.InspectListReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string inspectJson = 1;</code>
   * @return The inspectJson.
   */
  java.lang.String getInspectJson();
  /**
   * <code>string inspectJson = 1;</code>
   * @return The bytes for inspectJson.
   */
  com.google.protobuf.ByteString
      getInspectJsonBytes();
}
