/**
 * @fileoverview gRPC-Web generated client stub for CustomersSvc
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.4.2
// 	protoc              v3.12.4
// source: mes/Customers.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');


var google_protobuf_timestamp_pb = require('google-protobuf/google/protobuf/timestamp_pb.js')

var google_protobuf_duration_pb = require('google-protobuf/google/protobuf/duration_pb.js')

var google_protobuf_wrappers_pb = require('google-protobuf/google/protobuf/wrappers_pb.js')

var google_protobuf_empty_pb = require('google-protobuf/google/protobuf/empty_pb.js')
const proto = {};
proto.CustomersSvc = require('./Customers_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.CustomersSvc.CustomersClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.CustomersSvc.CustomersPromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.CustomersSvc.GetByKeyRequest,
 *   !proto.CustomersSvc.CustomersResponse>}
 */
const methodDescriptor_Customers_GetByKey = new grpc.web.MethodDescriptor(
  '/CustomersSvc.Customers/GetByKey',
  grpc.web.MethodType.UNARY,
  proto.CustomersSvc.GetByKeyRequest,
  proto.CustomersSvc.CustomersResponse,
  /**
   * @param {!proto.CustomersSvc.GetByKeyRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.CustomersSvc.CustomersResponse.deserializeBinary
);


/**
 * @param {!proto.CustomersSvc.GetByKeyRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.CustomersSvc.CustomersResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.CustomersSvc.CustomersResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.CustomersSvc.CustomersClient.prototype.getByKey =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/CustomersSvc.Customers/GetByKey',
      request,
      metadata || {},
      methodDescriptor_Customers_GetByKey,
      callback);
};


/**
 * @param {!proto.CustomersSvc.GetByKeyRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.CustomersSvc.CustomersResponse>}
 *     Promise that resolves to the response
 */
proto.CustomersSvc.CustomersPromiseClient.prototype.getByKey =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/CustomersSvc.Customers/GetByKey',
      request,
      metadata || {},
      methodDescriptor_Customers_GetByKey);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.CustomersSvc.GetByKeyRequest,
 *   !proto.CustomersSvc.CustomersResponse>}
 */
const methodDescriptor_Customers_GetByKeyJson = new grpc.web.MethodDescriptor(
  '/CustomersSvc.Customers/GetByKeyJson',
  grpc.web.MethodType.UNARY,
  proto.CustomersSvc.GetByKeyRequest,
  proto.CustomersSvc.CustomersResponse,
  /**
   * @param {!proto.CustomersSvc.GetByKeyRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.CustomersSvc.CustomersResponse.deserializeBinary
);


/**
 * @param {!proto.CustomersSvc.GetByKeyRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.CustomersSvc.CustomersResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.CustomersSvc.CustomersResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.CustomersSvc.CustomersClient.prototype.getByKeyJson =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/CustomersSvc.Customers/GetByKeyJson',
      request,
      metadata || {},
      methodDescriptor_Customers_GetByKeyJson,
      callback);
};


/**
 * @param {!proto.CustomersSvc.GetByKeyRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.CustomersSvc.CustomersResponse>}
 *     Promise that resolves to the response
 */
proto.CustomersSvc.CustomersPromiseClient.prototype.getByKeyJson =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/CustomersSvc.Customers/GetByKeyJson',
      request,
      metadata || {},
      methodDescriptor_Customers_GetByKeyJson);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.google.protobuf.Empty,
 *   !proto.CustomersSvc.CustomersSetResponse>}
 */
const methodDescriptor_Customers_GetAll = new grpc.web.MethodDescriptor(
  '/CustomersSvc.Customers/GetAll',
  grpc.web.MethodType.UNARY,
  google_protobuf_empty_pb.Empty,
  proto.CustomersSvc.CustomersSetResponse,
  /**
   * @param {!proto.google.protobuf.Empty} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.CustomersSvc.CustomersSetResponse.deserializeBinary
);


/**
 * @param {!proto.google.protobuf.Empty} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.CustomersSvc.CustomersSetResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.CustomersSvc.CustomersSetResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.CustomersSvc.CustomersClient.prototype.getAll =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/CustomersSvc.Customers/GetAll',
      request,
      metadata || {},
      methodDescriptor_Customers_GetAll,
      callback);
};


/**
 * @param {!proto.google.protobuf.Empty} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.CustomersSvc.CustomersSetResponse>}
 *     Promise that resolves to the response
 */
proto.CustomersSvc.CustomersPromiseClient.prototype.getAll =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/CustomersSvc.Customers/GetAll',
      request,
      metadata || {},
      methodDescriptor_Customers_GetAll);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.google.protobuf.Empty,
 *   !proto.CustomersSvc.CustomersSetResponse>}
 */
const methodDescriptor_Customers_GetAllJson = new grpc.web.MethodDescriptor(
  '/CustomersSvc.Customers/GetAllJson',
  grpc.web.MethodType.UNARY,
  google_protobuf_empty_pb.Empty,
  proto.CustomersSvc.CustomersSetResponse,
  /**
   * @param {!proto.google.protobuf.Empty} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.CustomersSvc.CustomersSetResponse.deserializeBinary
);


/**
 * @param {!proto.google.protobuf.Empty} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.CustomersSvc.CustomersSetResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.CustomersSvc.CustomersSetResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.CustomersSvc.CustomersClient.prototype.getAllJson =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/CustomersSvc.Customers/GetAllJson',
      request,
      metadata || {},
      methodDescriptor_Customers_GetAllJson,
      callback);
};


/**
 * @param {!proto.google.protobuf.Empty} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.CustomersSvc.CustomersSetResponse>}
 *     Promise that resolves to the response
 */
proto.CustomersSvc.CustomersPromiseClient.prototype.getAllJson =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/CustomersSvc.Customers/GetAllJson',
      request,
      metadata || {},
      methodDescriptor_Customers_GetAllJson);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.CustomersSvc.InsertRequest,
 *   !proto.CustomersSvc.CustomersResponse>}
 */
const methodDescriptor_Customers_Insert = new grpc.web.MethodDescriptor(
  '/CustomersSvc.Customers/Insert',
  grpc.web.MethodType.UNARY,
  proto.CustomersSvc.InsertRequest,
  proto.CustomersSvc.CustomersResponse,
  /**
   * @param {!proto.CustomersSvc.InsertRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.CustomersSvc.CustomersResponse.deserializeBinary
);


/**
 * @param {!proto.CustomersSvc.InsertRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.CustomersSvc.CustomersResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.CustomersSvc.CustomersResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.CustomersSvc.CustomersClient.prototype.insert =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/CustomersSvc.Customers/Insert',
      request,
      metadata || {},
      methodDescriptor_Customers_Insert,
      callback);
};


/**
 * @param {!proto.CustomersSvc.InsertRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.CustomersSvc.CustomersResponse>}
 *     Promise that resolves to the response
 */
proto.CustomersSvc.CustomersPromiseClient.prototype.insert =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/CustomersSvc.Customers/Insert',
      request,
      metadata || {},
      methodDescriptor_Customers_Insert);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.CustomersSvc.InsertRequest,
 *   !proto.CustomersSvc.CustomersResponse>}
 */
const methodDescriptor_Customers_InsertJson = new grpc.web.MethodDescriptor(
  '/CustomersSvc.Customers/InsertJson',
  grpc.web.MethodType.UNARY,
  proto.CustomersSvc.InsertRequest,
  proto.CustomersSvc.CustomersResponse,
  /**
   * @param {!proto.CustomersSvc.InsertRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.CustomersSvc.CustomersResponse.deserializeBinary
);


/**
 * @param {!proto.CustomersSvc.InsertRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.CustomersSvc.CustomersResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.CustomersSvc.CustomersResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.CustomersSvc.CustomersClient.prototype.insertJson =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/CustomersSvc.Customers/InsertJson',
      request,
      metadata || {},
      methodDescriptor_Customers_InsertJson,
      callback);
};


/**
 * @param {!proto.CustomersSvc.InsertRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.CustomersSvc.CustomersResponse>}
 *     Promise that resolves to the response
 */
proto.CustomersSvc.CustomersPromiseClient.prototype.insertJson =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/CustomersSvc.Customers/InsertJson',
      request,
      metadata || {},
      methodDescriptor_Customers_InsertJson);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.CustomersSvc.UpdateRequest,
 *   !proto.CustomersSvc.UpdateResponse>}
 */
const methodDescriptor_Customers_Update = new grpc.web.MethodDescriptor(
  '/CustomersSvc.Customers/Update',
  grpc.web.MethodType.UNARY,
  proto.CustomersSvc.UpdateRequest,
  proto.CustomersSvc.UpdateResponse,
  /**
   * @param {!proto.CustomersSvc.UpdateRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.CustomersSvc.UpdateResponse.deserializeBinary
);


/**
 * @param {!proto.CustomersSvc.UpdateRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.CustomersSvc.UpdateResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.CustomersSvc.UpdateResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.CustomersSvc.CustomersClient.prototype.update =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/CustomersSvc.Customers/Update',
      request,
      metadata || {},
      methodDescriptor_Customers_Update,
      callback);
};


/**
 * @param {!proto.CustomersSvc.UpdateRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.CustomersSvc.UpdateResponse>}
 *     Promise that resolves to the response
 */
proto.CustomersSvc.CustomersPromiseClient.prototype.update =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/CustomersSvc.Customers/Update',
      request,
      metadata || {},
      methodDescriptor_Customers_Update);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.CustomersSvc.DeleteRequest,
 *   !proto.CustomersSvc.DeleteResponse>}
 */
const methodDescriptor_Customers_Delete = new grpc.web.MethodDescriptor(
  '/CustomersSvc.Customers/Delete',
  grpc.web.MethodType.UNARY,
  proto.CustomersSvc.DeleteRequest,
  proto.CustomersSvc.DeleteResponse,
  /**
   * @param {!proto.CustomersSvc.DeleteRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.CustomersSvc.DeleteResponse.deserializeBinary
);


/**
 * @param {!proto.CustomersSvc.DeleteRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.CustomersSvc.DeleteResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.CustomersSvc.DeleteResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.CustomersSvc.CustomersClient.prototype.delete =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/CustomersSvc.Customers/Delete',
      request,
      metadata || {},
      methodDescriptor_Customers_Delete,
      callback);
};


/**
 * @param {!proto.CustomersSvc.DeleteRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.CustomersSvc.DeleteResponse>}
 *     Promise that resolves to the response
 */
proto.CustomersSvc.CustomersPromiseClient.prototype.delete =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/CustomersSvc.Customers/Delete',
      request,
      metadata || {},
      methodDescriptor_Customers_Delete);
};


module.exports = proto.CustomersSvc;

