// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/2023-08-09/Inspect.proto

package com.inspect;

public interface InspectReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:inspect.InspectReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 1;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
