// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mes/inspect/Inspect.proto

package com.inspect;

public interface GrpcDecimalOrBuilder extends
    // @@protoc_insertion_point(interface_extends:inspect.GrpcDecimal)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 units = 1;</code>
   * @return The units.
   */
  long getUnits();

  /**
   * <code>sfixed32 nanos = 2;</code>
   * @return The nanos.
   */
  int getNanos();
}
