// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/2023-08-09/2023-08-09/2023-08-09/Inspect.proto

package com.inspect;

public interface PartRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:inspect.PartRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string partCodeX = 1;</code>
   * @return The partCodeX.
   */
  java.lang.String getPartCodeX();
  /**
   * <code>string partCodeX = 1;</code>
   * @return The bytes for partCodeX.
   */
  com.google.protobuf.ByteString
      getPartCodeXBytes();
}
