name: Compile and Update Protobuf Files

on:
  push:
    paths:
      - '**/*.proto'

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.GRPC_AUTOCOMPILER_TOKEN }}

    - name: Install Protobuf Compiler
      run: sudo apt-get install -y protobuf-compiler

    - name: Install gRPC-Web Protobuf Plugin
      run: |
        wget https://github.com/grpc/grpc-web/releases/download/1.4.2/protoc-gen-grpc-web-1.4.2-linux-x86_64
        sudo mv protoc-gen-grpc-web-1.4.2-linux-x86_64 /usr/local/bin/protoc-gen-grpc-web
        sudo chmod +x /usr/local/bin/protoc-gen-grpc-web

    - name: Install TypeScript Protobuf Plugin
      run: npm install -g ts-protoc-gen

    # - name: Setup Go
    #   uses: actions/setup-go@v2
    #   with:
    #     go-version: 1.20

    # - name: Install Go Protobuf Plugin
    #   run: |
    #     go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.28
    #     go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.2

    # - name: Add Go Protobuf Plugin to Path
    #   run: echo "$(go env GOPATH)/bin" >> $GITHUB_PATH

    # - name: Install Dart Protobuf Plugin
    #   run: |
    #     sudo apt-get install -y dart
    #     pub global activate protoc_plugin

    # 각 언어별 컴파일 단계 추가
    - name: Compile Protobuf Files
      run: |
        find . -name "*.proto" | while read -r proto_file; do
          dir=$(dirname "$proto_file")
          filename=$(basename -- "$proto_file")
          name_no_ext="${filename%.*}"
          mkdir -p "$dir/$name_no_ext/csharp_out" "$dir/$name_no_ext/js_out" "$dir/$name_no_ext/ts_out" "$dir/$name_no_ext/java_out" "$dir/$name_no_ext/dart_out" "$dir/$name_no_ext/go_out"
          protoc --csharp_out="$dir/$name_no_ext/csharp_out" "$proto_file"
          protoc --js_out=import_style=commonjs,binary:"$dir/$name_no_ext/js_out" "$proto_file"
          # protoc --plugin="protoc-gen-ts=$(npm bin -g)/protoc-gen-ts" --ts_out="$dir/$name_no_ext/ts_out" "$proto_file"
          protoc --java_out="$dir/$name_no_ext/java_out" "$proto_file"
          # protoc --dart_out="$dir/$name_no_ext/dart_out" "$proto_file"
          # protoc --go_out="$dir/$name_no_ext/go_out" "$proto_file"
        done

    - name: Commit and push changes
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'github-actions@example.com'
        git add -A
        git commit -m "Update compiled protobuf files" || echo "No changes to commit"
        git push origin "${{ github.ref }}"
      env:
        GITHUB_TOKEN: ${{ secrets.GRPC_AUTOCOMPILER_TOKEN }}